const VARIEDAD_A_GRUPO: Record<string, string> = {
'SCARLET SPUR': 'ROJAS',
'EARLY RED ON':'ROJAS',
'ANGIOUS':'ROJAS',     
'RED CHIEF': 'ROJAS',  
'K OREGON II' :'ROJAS',
'ROYAL GALA' : 'GALA',
'GALAXY': 'GALA',
'ULTRARED GAL':'GALA',
'GALA PREMIUM':'GALA',
'BROOKFIELD': 'GALA', 
'BUCKEYE' : 'GALA' ,  
'PACIFIC GALA':'GALA',
'GALAVAL' :    'GALA',
'FUBRAX'  :   'FUJI' ,
'RAKU-RAKU':   'FUJI',
'CRIPPS PINK': 'CRIPPS PINK',
'ROSY GLOW' : 'CRIPPS PINK',
'AMBROSIA' :  'AMBROSIA',
'GRANNY SMITH':'GRANNYS',
'NICOTER' : 'KANZI'  , 
'60-6':  'IFO RED',
'46-2' :  'IFO RED',
'90-3' :  'IFO RED',
'MC51':  'MC',};
export default VARIEDAD_A_GRUPO;

//ROJAS', 'GALA', 'CRIPPS PINK', 'AMBROSIA', 'FUJI', 'KANZI', 'GRANNY SMITH'